### ISSUE TITLE
feat: add tests to cover a new user registration workflow

### ISSUE THREAD

**Issue by hmatalonga** [greenhub-project/farmer#9]
Add first batch of tests to cover the scenario of creating and verifying a new user

**Comment by soren5** [comment]
I've been reading the docs on this and I have a few questions about what exactly we want to cover.
Do we want to cover the entire user interaction aspect? [Laravel seems to support this](https://laravel.com/docs/5.7/dusk)
Or are we focusing on the internal logic of the registration?

**Comment by hmatalonga** [comment]
We won't be using Laravel Dusk at this point but we want to implement unit and feature tests for the registration and authentication (later on) workflow...

I think this post will give you a general overview:
https://medium.com/@DCzajkowski/testing-laravel-authentication-flow-573ea0a96318

So most of these tests will be under the [HTTP Tests](https://laravel.com/docs/5.7/http-tests).
